Update dependencies
ckeditor/ckeditor4-react pull request #298
Opened 2023-02-10 14:05 UTC by Comandeer

2023-02-14 10:01 UTC, KarolDawidziuk requested changes
Hi @Comandeer 
There are a few packages that we can update, especially the `typescript`, let's update it and we'll be ready to merge.

2023-02-14 15:00 UTC, Comandeer commented on package.json
>  		"nightwatch": "2.0.10",
We can't update `nightwatch` until #287 is fixed.

2023-02-14 15:01 UTC, Comandeer commented on package.json
>  		"typescript": "~4.7.4"
I would be cautious about updating TS as they don't use semver – there are probably some breaking changes. But I'll check that.

2023-02-14 15:07 UTC, Comandeer commented
@KarolDawidziuk, thx for the review! I've bumped the deps, except the `nighwatch` (which is blocked by #287).

2023-02-15 12:38 UTC, KarolDawidziuk approved these changes
Thanks, @Comandeer for the improvements.

LGTM! 🎉 

There is one failing test that we should check. It's can be related to an outdated version of the `nightwatch` package, so we should check if fixing https://github.com/ckeditor/ckeditor4-react/issues/287 will help.

2023-02-15 14:14 UTC, merged